apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${USER_NAME}
  name: ${USER_NAME}-role
rules:
- apiGroups:
  - ""
  - "apps"
  - "batch"
  - "extensions"
  resources:
  - "configmaps"
  - "pods"
  - "pods/attach"
  - "pods/exec"
  - "pods/log"
  - "services"
  - "deployments"
  - "statefulsets"
  - "cronjobs"
  - "jobs"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ${USER_NAME}
  name: ${USER_NAME}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${USER_NAME}-role
subjects:
- kind: User
  name: ${USER_NAME}
  namespace: ${USER_NAME}
